In [1]:
# -*- coding: utf-8 -*-
"""
   Introduction to Deep Learning (LDA-T3114)
   Skeleton Code for Assignment 1: Sentiment Classification on a Feed-Forward Neural Network

   Hande Celikkanat & Miikka Silfverberg
"""

'\n   Introduction to Deep Learning (LDA-T3114)\n   Skeleton Code for Assignment 1: Sentiment Classification on a Feed-Forward Neural Network\n\n   Hande Celikkanat & Miikka Silfverberg\n'

In [6]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import random

from data_semeval import *
from paths import data_dir

In [7]:
torch.manual_seed(42)

In [176]:
#--- hyperparameters ---

N_CLASSES = len(LABEL_INDICES)
N_EPOCHS = 100
LEARNING_RATE = 0.05
BATCH_SIZE = 100
REPORT_EVERY = 1
IS_VERBOSE = True

In [192]:
def make_bow(tweet, indices):
    feature_ids = list(indices[tok] for tok in tweet['BODY'] if tok in indices)
    bow_vec = torch.zeros(len(indices))
    bow_vec[feature_ids] = 1
    return bow_vec.view(1, -1)

def generate_bow_representations(data):
    vocab = set(token for tweet in data['training'] for token in tweet['BODY'])
    vocab_size = len(vocab) 
    indices = {w:i for i, w in enumerate(vocab)}
  
    for split in ["training","development.input","development.gold",
                  "test.input","test.gold"]:
        for tweet in data[split]:
            tweet['BOW'] = make_bow(tweet,indices)

    return indices, vocab_size

# Convert string label to pytorch format.
def label_to_idx(label):
    return torch.LongTensor([LABEL_INDICES[label]])

In [199]:
class FFNN(nn.Module):
    def __init__(self, vocab_size, n_classes, n_hidden_1, n_hidden_2, n_hidden_3):
        super(FFNN, self).__init__()
        
        self.fc1 = nn.Linear(vocab_size, n_hidden_1)
        self.fc2 = nn.Linear(n_hidden_1, n_hidden_2)
        self.fc3 = nn.Linear(n_hidden_2, n_hidden_3)
        self.fc4 = nn.Linear(n_hidden_3, n_classes)
        
    def forward(self, x):
        x = x.view(-1, vocab_size)
        out = F.relu(self.fc1(x))
        out = F.relu(self.fc2(out))        
        out = F.relu(self.fc3(out))        
        out = F.relu(self.fc4(out))
        out = F.softmax(out, dim=1)
        return out

In [194]:
#--- data loading ---
data = read_semeval_datasets(data_dir)
indices, vocab_size = generate_bow_representations(data)

In [195]:
print(vocab_size)

22032


In [196]:
print(model)

FFNN(
  (fc1): Linear(in_features=22032, out_features=500, bias=True)
  (fc2): Linear(in_features=500, out_features=200, bias=True)
  (fc3): Linear(in_features=200, out_features=100, bias=True)
  (fc4): Linear(in_features=100, out_features=3, bias=True)
)


In [197]:
model = FFNN(vocab_size, N_CLASSES, n_hidden_1=500, n_hidden_2=200, n_hidden_3=100) #add extra arguments here if you use
loss_function = torch.nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=LEARNING_RATE)

In [198]:
#--- training ---
for epoch in range(N_EPOCHS):
    total_loss = 0
    # Generally speaking, it's a good idea to shuffle your
    # datasets once every epoch.
    random.shuffle(data['training'])    

    for i in range(int(len(data['training'])/BATCH_SIZE)):
        minibatch = data['training'][i*BATCH_SIZE:(i+1)*BATCH_SIZE]
                
        x = [i['BOW'] for i in minibatch]
        labels = [label_to_idx(i['SENTIMENT']) for i in minibatch]
                
        x = torch.cat([i['BOW'] for i in minibatch], dim=-2)
        
        labels = torch.cat([label_to_idx(i['SENTIMENT']) for i in minibatch], dim=0)
                
        optimizer.zero_grad()
        predictions = model(x).view(100,3)
        
        loss = loss_function(predictions, labels)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        
    if ((epoch+1) % REPORT_EVERY) == 0:
        print('epoch: %d, loss: %.4f' % (epoch+1, total_loss*BATCH_SIZE/len(data['training'])))


<ipython-input-193-613107b4a78d>:16: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  out = F.softmax(out)


epoch: 1, loss: 1.0918
epoch: 2, loss: 1.0798
epoch: 3, loss: 1.0708
epoch: 4, loss: 1.0636
epoch: 5, loss: 1.0582
epoch: 6, loss: 1.0546
epoch: 7, loss: 1.0520
epoch: 8, loss: 1.0502
epoch: 9, loss: 1.0492
epoch: 10, loss: 1.0482
epoch: 11, loss: 1.0477
epoch: 12, loss: 1.0471
epoch: 13, loss: 1.0473
epoch: 14, loss: 1.0470
epoch: 15, loss: 1.0467
epoch: 16, loss: 1.0465
epoch: 17, loss: 1.0466
epoch: 18, loss: 1.0461
epoch: 19, loss: 1.0461
epoch: 20, loss: 1.0459
epoch: 21, loss: 1.0460
epoch: 22, loss: 1.0456
epoch: 23, loss: 1.0451
epoch: 24, loss: 1.0449
epoch: 25, loss: 1.0445
epoch: 26, loss: 1.0443
epoch: 27, loss: 1.0434
epoch: 28, loss: 1.0427
epoch: 29, loss: 1.0421
epoch: 30, loss: 1.0410
epoch: 31, loss: 1.0397
epoch: 32, loss: 1.0385
epoch: 33, loss: 1.0365
epoch: 34, loss: 1.0343
epoch: 35, loss: 1.0316
epoch: 36, loss: 1.0286
epoch: 37, loss: 1.0245
epoch: 38, loss: 1.0198
epoch: 39, loss: 1.0149
epoch: 40, loss: 1.0100
epoch: 41, loss: 1.0040
epoch: 42, loss: 0.9939
e

In [200]:
#--- test ---
correct = 0
with torch.no_grad():
    for tweet in data['test.gold']:
        gold_class = label_to_idx(tweet['SENTIMENT'])
        gold_bow = tweet['BOW']
                
        prediction_tensor = model(gold_bow)
                
        predicted = prediction_tensor.max(1)[1]
        
        is_correct = predicted == gold_class
        
        if is_correct:
            correct += 1
        
        if IS_VERBOSE:
            print('TEST DATA: %s, GOLD LABEL: %s, GOLD CLASS %d, OUTPUT: %d' % 
                 (' '.join(tweet['BODY'][:-1]), tweet['SENTIMENT'], gold_class, predicted))

    print('test accuracy: %.2f' % (100.0 * correct / len(data['test.gold'])))

<ipython-input-193-613107b4a78d>:16: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  out = F.softmax(out)


tensor([[0.0393, 0.3215, 0.6392]])
TEST DATA: dec 21st 2012 will be know not as the end of the world but the baby boom ! #2012shit, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0054, 0.9817, 0.0128]])
TEST DATA: mt @lccsy #syria , deir ezzor : ali bashar al-theeb was martyred . he was a soldier of the free syrian army . wednesday , 3 october 2012 ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0034, 0.0034, 0.9933]])
TEST DATA: @macmiller hate my life , because i can't see you at the roskilde festival on saturday , promise me to come back again , soon ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[9.8911e-04, 9.8911e-04, 9.9802e-01]])
TEST DATA: excited for fri , not so i can get smashed but so i can go to the garden centre , look at the xmas display and have a coffee #wtf #grannyalert, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0232, 0.8221, 0.1546]])
TEST DATA: just got the ics update from sony on my sola ( apparently it was released on 

tensor([[0.0021, 0.0021, 0.9957]])
TEST DATA: @brookeofmidgard i'm sitting here with my belt , in jean shorts watching cena win his first title . i think we tie for 1st my friend xd, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0011, 0.9978, 0.0011]])
TEST DATA: idk how im gone make it to total sports tomorrow for selection sunday, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0200, 0.8054, 0.1746]])
TEST DATA: team ck vs demolition on november 17th at the american legion post 80 , main st . in binghamton ny . get your tickets now ! http://t.co/bieeefzd, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0310, 0.6078, 0.3612]])
TEST DATA: @charliewaters i laughed a little , but not sharing them out with anyone . will the weather be good tomorrow for boris bikes ?, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0010, 0.0010, 0.9980]])
TEST DATA: @gma my daughter @jordynking17 will be 14 on december 17th ! we r going to see buddy @ the kirby center in

tensor([[0.0322, 0.1246, 0.8431]])
TEST DATA: watching jiujitsu matches all day long , getting ready for sunday !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[7.6873e-04, 9.9846e-01, 7.6873e-04]])
TEST DATA: the san diego #chargers expect wide receivers eddie royal and malcom #floyd to play in monday night's game against the denver #broncos, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0244, 0.0672, 0.9084]])
TEST DATA: it only took 5 days for them to fix the broadband outage . china telecom may be improving ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0401, 0.5458, 0.4141]])
TEST DATA: omigod you guys i get to see holy motors tomorrow ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[8.7137e-04, 9.9826e-01, 8.7137e-04]])
TEST DATA: everyday i'm like " shit is it the 17th yet ! ? did i miss the kiryu project ! ? " > <, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0047, 0.9881, 0.0072]])
TEST DATA: becoming dangerously obsessed wit

tensor([[0.0038, 0.9909, 0.0052]])
TEST DATA: that should be andy lee's 3rd punt today down inside the 5 ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.8859e-04, 9.9962e-01, 1.8859e-04]])
TEST DATA: rndm has a beef with music videos debut album " acts " out on oct 30 , 2012 https://t.co/ap2ynm2s, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[6.5344e-04, 6.5344e-04, 9.9869e-01]])
TEST DATA: @therobindiaz watching on livestream tonight you guys put on a hell of a show as always , see you in binghamton ny next saturday love u guys, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0055, 0.0055, 0.9890]])
TEST DATA: tomorrow is the mother's day ... i love you , mom ^ ___ ^, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0351, 0.2532, 0.7117]])
TEST DATA: @vivavhs haha . i've got to cut down mate , not looking forward to going through the warners . might try and sort small set tomorrow vestron ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[9.

tensor([[1.0547e-04, 9.9979e-01, 1.0547e-04]])
TEST DATA: mt @oakartenthsiast : sculptors ! have you submitted for new art park on telegraph & 19th in #oakland ? 36 hours left ! http://t.co/ivcqwekz, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0033, 0.0033, 0.9934]])
TEST DATA: de la soul's eye know playing in pret - the perfect monday tonic !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[7.2918e-05, 9.9985e-01, 7.2918e-05]])
TEST DATA: the home & garden show with ken brown , live from menne nursery , sat sept 22 , 11 am . listen to wben am 930 and call in with your questions ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[5.3487e-04, 9.9893e-01, 5.3487e-04]])
TEST DATA: sp says quota bill unconstitutional - samajwadi party on wednesday dubbed as " unconstitutional " the bill to provide ... http://t.co/zi1ny8gt, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0015, 0.9970, 0.0015]])
TEST DATA: blueberry muffins last night , brownies tonight , oreo

tensor([[1.7851e-04, 1.7851e-04, 9.9964e-01]])
TEST DATA: @strideso thanks ! the result may be more sidney crosby than lanny mcdonald , but i will post my pics with pride either way ;), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0380, 0.1320, 0.8300]])
TEST DATA: omg jonghyun is following his hyung by giving me 2nd hand embarrassment feels . xd what are you cnblue dorks . http://t.co/m62gxjrz, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0289, 0.0733, 0.8978]])
TEST DATA: @peeeeekabooo serious it 2nd while naruto still first of course !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0104, 0.9559, 0.0337]])
TEST DATA: pretty sure it's the end of the school week now , friday is the end right , or is it wednesday ? i forget, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0014, 0.0014, 0.9972]])
TEST DATA: @maiteoficial today is 1st day in school .. wish me luck , maite ! ! ! #tqm, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0016, 

tensor([[0.0220, 0.0759, 0.9021]])
TEST DATA: @syddie yes . i'm thinking feb / march , possibly to include holi ! ? i want to play with all the colors !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0015, 0.9969, 0.0015]])
TEST DATA: i think i may have a slight ( um maybe a severe ) addiction to the vanilla fudge quality streets . they're irresistable, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0016, 0.9967, 0.0017]])
TEST DATA: gawd , uan on nickelodeon tomorrow . - ___ - " remind me to not get home before 6 . i hate watching the boys on nick , it just gets to me . >:(, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[4.4343e-04, 4.4343e-04, 9.9911e-01]])
TEST DATA: @karminmusic just found out about binghamton ny next saturday - can't wait ! :) #spiediefest #roadtrip, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0218, 0.0393, 0.9389]])
TEST DATA: your inspirational quotes on twitter / feb never really got to me . but oh damn ur pics of them 

tensor([[0.0010, 0.9980, 0.0010]])
TEST DATA: i want to go to grand bend for may 24, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0025, 0.0025, 0.9949]])
TEST DATA: got my sunday sussed out start with russian game , mk dons , edinburgh derby for starters . !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0133, 0.0159, 0.9708]])
TEST DATA: on wednesday we welcome chef and restaurateur antonio carluccio to the store to sign copies of his new book . http://t.co/8pq0sccl, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[9.4273e-04, 9.9811e-01, 9.4273e-04]])
TEST DATA: watch the sneak peek clip for tomorrow's all-new " how to rock a high school sensation ! " http://t.co/t8qwag1k, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0015, 0.9971, 0.0015]])
TEST DATA: @mandiieekillaaa are you going to laidback luke tomorrow ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0081, 0.9633, 0.0285]])
TEST DATA: jose iglesias homers w / the #rays down 4-1 

TEST DATA: @dannycatedlover @amyanneturner @annahades @gealingeman i think that the 2nd place on melodifestivalen gives the points on eurovision ! ;), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0363, 0.2626, 0.7011]])
TEST DATA: billy gillispie is awful . nothing's worse than him being your coach . unless it's losing to him in the 2nd round of the 2007 ncaa tournament ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0271, 0.7685, 0.2043]])
TEST DATA: @dimebagwillsy3 @rollingstones have you been watching crossfire hurricane , the documentary , last 2 saturday nights ? superb ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[9.6647e-06, 9.9998e-01, 9.6647e-06]])
TEST DATA: @piersmorgan relax , you can now concentrate on finishing 4th and which one of wilshere , carzorla or vermalen you want to sell to city ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0067, 0.0067, 0.9866]])
TEST DATA: sunday night wrap-up : manning , broncos roll saints : h

tensor([[0.0057, 0.9848, 0.0096]])
TEST DATA: duke energy ceo jim rogers addressed the democratic national convention thursday afternoon http://t.co/d9cftvsc, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0069, 0.0069, 0.9861]])
TEST DATA: peru wants 1d world tour let's go trending trending trending till we see the sun, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[7.0139e-04, 7.0139e-04, 9.9860e-01]])
TEST DATA: after the great east japan earthquake on march 11 last year , the performance of the spectacularly tall tokyo sky ... http://t.co/mvmgvfqm, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0359, 0.4532, 0.5109]])
TEST DATA: sbc red lions clinch win first finals game over the letran knights , 62-60 . next game will be on saturday , 6pm @ smart araneta coliseum ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[2.1829e-04, 9.9956e-01, 2.1829e-04]])
TEST DATA: who else is going to see catelynn and tyler at anthony hall on thursday ?, GOLD LABEL: ne

TEST DATA: @excda @bryanadams bryan's australian tour is on april 2013 i just bought the tickets yesterday for the sydney concert are you going ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.4513e-04, 1.4513e-04, 9.9971e-01]])
TEST DATA: @ideenyc and i feel the exact same way about allderdice haha , its my 2nd favorite project he's released ( behind k & oj ) . hes making good music, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0485, 0.5033, 0.4482]])
TEST DATA: @liebetreuebrai lol idek what phase my shit is .. i just know morris hall 3rd floor hell, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0038, 0.0038, 0.9924]])
TEST DATA: good night everyone tomorrow is the last day of star wars weekends :( </3, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[2.1589e-04, 9.9957e-01, 2.1589e-04]])
TEST DATA: lance dehm racing qualified 11th of 130 cars at the ump fall nationals hosted at eldora speedway . click here for photos http://t.co/4wecevjw, GOLD L

TEST DATA: @reginazernay hey regina , i thought you may like this on bbc rolling stones : crossfire hurricane : part two http://t.co/npxiz7yh tony, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0033, 0.0033, 0.9935]])
TEST DATA: heather is like the serpent in the garden trying 2 entice info from mcbain ! michael easton , dont ever go away that long ! watching tues #gh ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[1.7822e-04, 9.9964e-01, 1.7822e-04]])
TEST DATA: or , you know , some version of it . in 4th grade , i was writing a novel called prisoners of radio city and @disneyhyperion didn't exist yet !, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0163, 0.9089, 0.0748]])
TEST DATA: " bridging the gap " breakfast sat morning nth highld fellowship hall . looing for all black leadership . one front . 9 am i . m . a . l . c ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0192, 0.8621, 0.1186]])
TEST DATA: facts about friday's matchup with fresn

tensor([[0.0243, 0.0882, 0.8875]])
TEST DATA: brilliant burns stops mitchell in 4th : kevin mitchell's bid to win the wbo lightweight title ended in failure on ... http://t.co/gzxrbvmm, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[6.1928e-05, 6.1928e-05, 9.9988e-01]])
TEST DATA: excited for the colts game with my love , @itsthegwebb41 sunday :), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0057, 0.9772, 0.0171]])
TEST DATA: in the news ! the ballad of emmett till in mysa by deborah martin . see the final performance on sunday @ 3:00 ... http://t.co/4sdgdcli, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[4.3275e-04, 9.9913e-01, 4.3275e-04]])
TEST DATA: @imyoonique she is the new member beside danee . the 8th member ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0039, 0.0039, 0.9922]])
TEST DATA: c'mon @teamsky get today out the way & its yours , the maillot jaune will stay on @bradwiggins back & history will b made #believeinbritain, GOLD LABEL:

tensor([[0.0029, 0.9934, 0.0038]])
TEST DATA: we're going tomorrow ! @fabulous_miami multi chamber of commerce event at nikki beach miami 8/ 8/ 12 http://t.co/wt1xjbpq, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[8.7360e-04, 9.9825e-01, 8.7360e-04]])
TEST DATA: embarrassed cardinals try to pick up the pieces : tempe , ariz . ( ap ) - embarrassed on monday night , the arizona ca ... http://t.co/pttdl12j, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0049, 0.0049, 0.9902]])
TEST DATA: fuck you bitch . mitchie made me , she was like " c'mon drew she's cute " ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0067, 0.0067, 0.9866]])
TEST DATA: giveaway time ! reply with your favorite letter for your chance to win tix to rndm in the mainroom tomorrow night http://t.co/kd3gj4af, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0167, 0.8913, 0.0920]])
TEST DATA: our next broadcast is monday when the soccer team takes on seaholm in the first game of the mh

tensor([[9.6756e-04, 9.9806e-01, 9.6756e-04]])
TEST DATA: @djrobingalloway : mrs arrested 4 streaking @ crufts . judge gave her 2nd place with her puppies but said her afghan could do with a trim ", GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0196, 0.8575, 0.1229]])
TEST DATA: @carrieunderwood @hunterhayes @hhroadguy please clarify if the show in atlantic city on november 9th is still on ! ? ! ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0040, 0.9868, 0.0092]])
TEST DATA: of all the receivers with at least 20 receptions , cecil shorts is 2nd in average ypc ( 20 ) . behind vincent jackson ( 21.6 ), GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0014, 0.9972, 0.0014]])
TEST DATA: is anyone going to runrig tomorrow, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0043, 0.0043, 0.9915]])
TEST DATA: if gerald green doesn't have the most hops in the league then he definitely is a strong 2nd ! ! http://t.co/nim4xfkg, GOLD LABEL: positive, GOLD CLASS

TEST DATA: tune into the kicx winning weekend with @neilanthonylive 4 your chance 2 c @doc_walker next saturday at the kee to bala aboard the kicx bus, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0400, 0.4073, 0.5527]])
TEST DATA: check http://t.co/xiyawvwt for all the reaction to saturday's 2-1 win over bolton wanderers #millwall, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[8.3137e-04, 9.9834e-01, 8.3137e-04]])
TEST DATA: i'm going to such gold at hoosier dome in indianapolis , in - nov 1 http://t.co/qnrypptp, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[3.4947e-04, 3.4947e-04, 9.9930e-01]])
TEST DATA: everyday remind yourself you are the best ! happy international women's day ! http://t.co/5rphohmc, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0014, 0.9972, 0.0014]])
TEST DATA: @jethronaldo7 the reason why i'm telling you hmv is kasi may special editions yan and shit : >, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0029, 0.0029

tensor([[6.4522e-04, 6.4522e-04, 9.9871e-01]])
TEST DATA: " if i should die tomorrow , i will have no regrets . i did what i wanted to do , you can't expect much more from life " - bruce lee, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[1.0592e-04, 9.9979e-01, 1.0592e-04]])
TEST DATA: trip begs bree to tell him what happened the night of alejandro's murder as in the series finale of #desperatehousewives , abc sunday at 9pm, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.4066e-04, 9.9972e-01, 1.4066e-04]])
TEST DATA: im going to watch the mtn 8 final tomorrow at the magnificent orlando stadium in soweto, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0113, 0.9519, 0.0369]])
TEST DATA: bristol city haven't been in this match since eagles scored in the 31st minute . this is my bolton wanderers . #bwfc, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0326, 0.1626, 0.8048]])
TEST DATA: shinee's taemin and jonghyun will be recording for " strong heart " t

tensor([[0.0288, 0.1647, 0.8065]])
TEST DATA: got 2nd row tix for primus at the kirby center ! 1st concert tour in 3d with surround sound !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0241, 0.7701, 0.2058]])
TEST DATA: kenny lofton , who makes his debut on the hall of fame ballot today , is the 1st former #arizonawildcats to ever appear on a hoff ballot ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0104, 0.0104, 0.9792]])
TEST DATA: @nickelodeontv may you please show how to rock from episode 1 and so on ... i cant blieve theres no more how to rock, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[3.5875e-04, 9.9928e-01, 3.5875e-04]])
TEST DATA: i may or may not be jumping around the lounge to some random boy band on mtv hits, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0096, 0.9687, 0.0217]])
TEST DATA: dang , i want some crawfish right now . #may http://t.co/bycu4wnf, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0246, 0.0399, 0.93

tensor([[0.0250, 0.8172, 0.1578]])
TEST DATA: going to the fair on sunday .., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[7.8129e-04, 9.9844e-01, 7.8129e-04]])
TEST DATA: what does it take to be an entrepreneur ? find out from friars in fashion tomorrow , thu , 4pm , bowab in smith center http://t.co/qwkiz93a, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0048, 0.9857, 0.0095]])
TEST DATA: its going down this saturday at rum runners st cloud ... btw where the party at tonight ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.4979e-04, 1.4979e-04, 9.9970e-01]])
TEST DATA: hope the weather is like this for ironman wales . lovely and sunny yet not too warm . good luck all . may the wind be behind you all the way ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0111, 0.9566, 0.0323]])
TEST DATA: mohammad hirzallah ( 24 ) from rafah ( gaza strip ) died thursday from injuries sustained in an israeli air strike a day earlier, GOLD LABEL: neutral, GOLD C

tensor([[4.1596e-05, 4.1596e-05, 9.9992e-01]])
TEST DATA: @macklemore it's my best friends 19th birthday today and she loves you ! we saw you at soundset on sunday , show my girl @heyitsturr some love, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0012, 0.0012, 0.9976]])
TEST DATA: tonight at home vs summersville ! good luck to our boys . play with the same fire you ended with saturday against thayer & alton #lovemyealges, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0026, 0.0026, 0.9948]])
TEST DATA: too much sun today ! .. at least i got one picture with ma girl @daniartaud @ pomona fairplex http://t.co/mr1i7ijf, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0325, 0.3950, 0.5726]])
TEST DATA: ep #126 : psychobilly friday from space ! - terminal signal : psychobilly from mad sin , nekromantix and the quakes ! ... http://t.co/6klodjyr, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0222, 0.8388, 0.1391]])
TEST DATA: this female said kirko bang

TEST DATA: time to get nekkid with filter free friday ( 3/8 / 2012 ) http://t.co/neodn26b only @ the original global #iphoneography community @ #mobitog ..., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.8989e-04, 1.8989e-04, 9.9962e-01]])
TEST DATA: they might be giants ' version of " there's a great big beautiful tomorrow " ... tmbg + disney ... awww , pandora , you do know me ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0068, 0.0068, 0.9864]])
TEST DATA: yes , it is us : " ufo sighting in surprise , arizona on october 31st 2012 - it was an orange orb travlin ... http://t.co/ezqcqw91 " #aliens, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0032, 0.9925, 0.0043]])
TEST DATA: live semi-finals this thursday night 9-10 pm on cw network . america votes . please share with friends . #teamjordan http://t.co/adiyfyrg, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0043, 0.0043, 0.9914]])
TEST DATA: big congrats to @gregy20723 4winning the main even

TEST DATA: @rumpfshaker @therickwilson more good news may o and carter can have a beer summit in the gaza strip, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0021, 0.0021, 0.9957]])
TEST DATA: thanks to moomba , i've been cruising wi the medicare since april 2011 . today i decided to finally go get it done ! #abouttime, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[8.8630e-04, 8.8630e-04, 9.9823e-01]])
TEST DATA: @alitweel guess im a bit father back for classics " inn of the 6th happiness " , " pennies from heaven " , " to sir with love " :), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0021, 0.9950, 0.0029]])
TEST DATA: first hasek now modano want to come back ... who's next mario lemieux for the 4th time !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0014, 0.9973, 0.0014]])
TEST DATA: i used to watch abc sunday night movies with the fam , now we watch #newsroom on hbo , how times have changed ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1

tensor([[0.0038, 0.9895, 0.0066]])
TEST DATA: tomorrow thorbjorn will be paired with richard bland and will be teeing off at 11:41 am ( gmt + 1 ) ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[5.5280e-04, 9.9889e-01, 5.5280e-04]])
TEST DATA: photo : pagara's back with a vengeance ; knocks out montoya in 6th round , takes wbo title . http://t.co/9gyhfmsh, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0027, 0.9937, 0.0036]])
TEST DATA: friday's top 10 : gerald green rises above the everyone in friday's top 10 . http://t.co/6sxyhilp, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0325, 0.5262, 0.4413]])
TEST DATA: super saturday is on tomorrow at westfield parramatta . one day to grab some pre christmas bargins . for one day ... http://t.co/r1pubfcj, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0074, 0.0074, 0.9851]])
TEST DATA: don't miss carmen on the 100th episode of 90210 airing tomorrow night 8/ 7c on the cw network !, GOLD LABEL: positive, GO

TEST DATA: oomf just told me league pass is free till the 6th, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0049, 0.0049, 0.9902]])
TEST DATA: winner - our train station at glossop has just been awarded 1st in best station development category at national award ceremony . #teamwork, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0087, 0.9647, 0.0266]])
TEST DATA: general dynamics interview invitational event friday , 10/26 / 12 at the sheraton hotel bwi airport at genera ... http://t.co/reznkhq2 #jobs, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0012, 0.9975, 0.0012]])
TEST DATA: koreatown , calif . - - a man allegedly shot his former boss in the head thursday at a commer http://t.co/rkr3thri, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0103, 0.0103, 0.9794]])
TEST DATA: someone must not be too happy with the hired help in sewickley : sidney crosby's image removed from #pens mobile app cover on thursday . #nhl, GOLD LABEL: negative, GOLD CL

tensor([[0.0138, 0.9277, 0.0585]])
TEST DATA: watched " the ladykillers " this afternoon . the perfect film for saturday afternoon . or any other time of the week ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0331, 0.1913, 0.7756]])
TEST DATA: @snuep @sarahtingle our annual clothing drive for the open closet is during the 1st week of march for international women's day !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0265, 0.0940, 0.8794]])
TEST DATA: @andreaxx33 andreaaa :) are you going to the fair on saturday ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0224, 0.0480, 0.9296]])
TEST DATA: july 16 , 8p m est , big time movie will be premiering on ytv with one direction commenting during commercials ( via @1dupdatescanada ), GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0122, 0.0122, 0.9756]])
TEST DATA: inkigayo with @hardyz_gurl14 yay this is our saturday night <3 #kpop_stream http://t.co/elco5nuk, GOLD LABEL: neutral, GOLD CLASS 1, OUT

tensor([[5.9773e-05, 9.9988e-01, 5.9773e-05]])
TEST DATA: the view from the 24th floor @ mgm grand at foxwoods http://t.co/wif2jjdw, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.9990e-04, 1.9990e-04, 9.9960e-01]])
TEST DATA: good luck and lots of energy to @cderycke , who is competing in the ironman wales this sunday ! ! come on chris !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[3.8305e-04, 3.8305e-04, 9.9923e-01]])
TEST DATA: thanks , lyndsey ... hairstrks sometimes red , sometimes pink ! @queeneasygreen we're going to see the ladykillers in nott'ham tomorrow ! !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0045, 0.9892, 0.0063]])
TEST DATA: i was just reminded by @johngmcnutt that tomorrow is international talk like a pirate day . http://t.co/kr7zmkej #whimsy, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[3.2676e-04, 9.9935e-01, 3.2676e-04]])
TEST DATA: will texans see the old mario williams on sunday ? ... http://t.co/nc9z1sd4 #nfl #buffa

tensor([[0.0013, 0.0013, 0.9974]])
TEST DATA: huge fight in the chargers game ! good game for two medicore teams . next thursday we get colts.vs jags ... ugh, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0083, 0.0083, 0.9835]])
TEST DATA: i got the job at claytons ! (: i start monday doing sheetrock (: #moneymakin, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0182, 0.0234, 0.9584]])
TEST DATA: turns out the issue we've been having w / production is because some of our computers may not update time from internet ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0292, 0.6157, 0.3551]])
TEST DATA: going out tomorrow for the first time in 11 days to my dads for dinner first watching dons v preston on sky sports 2 tho #steppingstones, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[4.8409e-04, 4.8409e-04, 9.9903e-01]])
TEST DATA: @dionwaiters3 good luck on thursday . i know a lot of cuse fans who are gonna be following you & the cavs very closely & sup

TEST DATA: stone brewing just got added to our list of brewers attending the 2nd ann riverside blues & bbq ! http://t.co/vuee4wyw, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0278, 0.7296, 0.2425]])
TEST DATA: who's coming to the beatport festival july 20th to dance there asses off ! [ shannon leto on twitter ], GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0028, 0.9923, 0.0049]])
TEST DATA: la liga : betis march on , malaga held to draw : real betis moved up to fourth in the table af ... http://t.co/dqsscacc http://t.co/idwtfszf, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0165, 0.9165, 0.0671]])
TEST DATA: #celebrate your new arrival with a naming ceremony . meet @themembox at mum n baby fair colne valley garden centre huddersf'd sun 28 10.30, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0325, 0.3760, 0.5915]])
TEST DATA: everyone pls come check out necie's carnival tomorrow ! ! ! we sell all the food you buy at a carnival funnel cakes 

TEST DATA: london yesterday was amazing , sun beer , hyde park , mexicans . brazilians , boris bikes just incredible day, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[4.2957e-04, 9.9914e-01, 4.2957e-04]])
TEST DATA: @mittromney <u> + not going there > w bush years , dennis kucinich speaks @ dnc on aug . 26 , ' 08 wake up america http://t.co/s8b5cfn5, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0252, 0.7873, 0.1875]])
TEST DATA: @chelseamorg @blakeshelton blake get ready for the wild girls in ohio june 15th hurry up ! ! !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0048, 0.9863, 0.0089]])
TEST DATA: @doug_zamensky @suzzifiazco @ianasbury #hard #dayofthedead weekend just got a bit weirder . chateau marmont on sunday ? what ? !, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[5.9159e-04, 9.9882e-01, 5.9159e-04]])
TEST DATA: @sofiaferarri i'm going to feedme in ohio june 3rd, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0023, 0.9948, 0.

tensor([[0.0116, 0.9498, 0.0386]])
TEST DATA: hollywood actress sharon stone , 55 , chaired an aids research fund raiser despite being hospitalised with a migraine on friday ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.5476e-05, 9.9997e-01, 1.5476e-05]])
TEST DATA: " notice : maintenance this saturday ( oct 6 ) with planned service interruption . " - tumblr ( dashboard ), GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[8.4089e-05, 9.9983e-01, 8.4089e-05]])
TEST DATA: ronald reagan sr . in doral . last town hall before nov 6 , 6:30 pm tonight ! come out , get informed on #vote222, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0121, 0.9399, 0.0481]])
TEST DATA: my new theory ... petraeus told romney no to benghazi at the debate cuz he was planning to blow it up later ... can u say #october suprise ?, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0140, 0.9279, 0.0580]])
TEST DATA: did you know that over half our workforce are nursing staff ( 57 % )

TEST DATA: never have i felt this tired i had more fucking energy on the monday morning if leeds festival for christ sake, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0020, 0.9959, 0.0020]])
TEST DATA: forget league's super saturday , @cnn has super storm sandy . name aside the coverage has been first class, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[3.5520e-07, 1.0000e+00, 3.5520e-07]])
TEST DATA: late surge carries unc past shaw : six minutes into the second half at the smith center on friday night , north ... http://t.co/awg9bynh, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0036, 0.0036, 0.9929]])
TEST DATA: @mattbarkley scant wait leave for l . a . tomorrow morning from omaha , ne to watch the trojans go duck hunting ! see yahoo on the field !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0075, 0.9666, 0.0259]])
TEST DATA: if you're going to saturday's ben sollee show , make sure to stop by and see abby at the kftc table , and if you

tensor([[7.8164e-04, 7.8164e-04, 9.9844e-01]])
TEST DATA: now that i can finally sleep ... can't wait to work for another like ... 8 hours or so tomorrow .. and a doctor appt ... yay ..., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0042, 0.9882, 0.0077]])
TEST DATA: i'm going to miguel migs at nikki beach miami in miami , fl - mar 18 http://t.co/oec34rdr, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0358, 0.1103, 0.8539]])
TEST DATA: michael dyer got kicked out of his 2nd school . smh . he had it made . why throw away your talent like that . smfh, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0012, 0.9976, 0.0012]])
TEST DATA: deadly israeli strike , fire from gaza mar truce : a deadly israeli airstrike into the gaza strip and rocket and ... http://t.co/e0h27mcg, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0033, 0.0033, 0.9935]])
TEST DATA: in celebration of mother's day in #argentina , we will be treating mom's to a glass of bubbly with #

TEST DATA: getting sick right before the ucla football game on saturday < < <, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0112, 0.9534, 0.0355]])
TEST DATA: @qldlabor c'mon now that's unfair i'm sure it's just because his mum forgot to put his shirt in the drier #griffithvotes, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0289, 0.6879, 0.2832]])
TEST DATA: who wants to go with me to the bhc tomorrow to the meet & greet with tyler & catelynn from teen mom at 8 ?, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[1.0491e-05, 9.9998e-01, 1.0491e-05]])
TEST DATA: so what happened to kony 2012 " cover the night " on april 20 ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0077, 0.0077, 0.9846]])
TEST DATA: ucla coach ben howland on other pac - 12 teams , " i think cal may have the best pair of guards in the conference . ", GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0013, 0.0013, 0.9975]])
TEST DATA: happy 4th from the studykas :) @ pom

tensor([[0.0086, 0.9657, 0.0258]])
TEST DATA: #maction . i mean , way to go , bearcats . made up for a 4th quarter from hell with one huge drive ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0324, 0.2224, 0.7451]])
TEST DATA: doing a tv note about hallmark movie : , " a smile as big as the moon , " about teacher's fight to take kids to #nasa #space camp . airs abc sunday, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0026, 0.0026, 0.9949]])
TEST DATA: dont miss author jonathan kozol will be at @barnesnoble wed . at 7:00 pm discussing his new book " fire in the ashes " ! http://t.co/ds3txjbi, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[5.1076e-05, 9.9990e-01, 5.1076e-05]])
TEST DATA: getting ready to join 1st kilmacolm scout group at the remembrance service . vital that young people understand what today is about #iscout, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0407, 0.2982, 0.6611]])
TEST DATA: #tedxsendai is october 10th http://t.co/m

tensor([[0.0183, 0.9108, 0.0709]])
TEST DATA: oh mehdi hasan . being anti abortion may not make you any less of a lefty but it does diminish you . and that's a shame ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0032, 0.0032, 0.9936]])
TEST DATA: watching wansapanataym with nephew , so grade schoool kids touch screen na rin mga cellphone ? noong elem ako cool na yun may mga beeper haha, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0314, 0.7350, 0.2336]])
TEST DATA: thinking i'm going to charleston tomorrow !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[4.6888e-04, 9.9906e-01, 4.6888e-04]])
TEST DATA: would it be crazy if i asked to go to washington dc nov 17 for the joseph kony march ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0020, 0.0020, 0.9961]])
TEST DATA: sunday announcements from the youths 1.youths want to thank elder opit and experts from usaid for the wonderful ... http://t.co/ikxnxniv, GOLD LABEL: positive, GOLD CLASS 2, OUTP

tensor([[0.0098, 0.9698, 0.0204]])
TEST DATA: man it's tuesday you shouldn't be eating thanksgiving leftovers still, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[7.7819e-04, 7.7819e-04, 9.9844e-01]])
TEST DATA: @justinbieber hi , my name is dayle , abd you're my inspiration ! :) ( rt / follow if you see this ? ) 47, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[4.9293e-04, 9.9901e-01, 4.9293e-04]])
TEST DATA: @daverosin please may my band make a cover of scream to perform for our school & maybe upload to youtube with yours and hedley's permission ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0387, 0.4869, 0.4744]])
TEST DATA: @educators don't miss jonathan kozol , author of " fire in the ashes " sept 11 @phoenix college 7pm discussing public school issues #educators, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0015, 0.9970, 0.0015]])
TEST DATA: @gmorerad gav , what the eff is this ? i've just gotten home from roskilde festival , 1st internet

tensor([[3.5376e-04, 9.9929e-01, 3.5376e-04]])
TEST DATA: seven penny stocks on the move with heavy volume for thursday : converted organics inc . ( pink : coin ) traded as hig ... http://t.co/lne55fyp, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0012, 0.0012, 0.9977]])
TEST DATA: @marnilittle hey marni ! are you going to be at the kings next sunday ? i would love to be able to meet you ! xx, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0318, 0.1005, 0.8677]])
TEST DATA: @katielamica we wont know until tomorrow ! i think it is between colton and herman !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0011, 0.0011, 0.9977]])
TEST DATA: i get to go see my endo tomorrow . let just say i'm excited about that . can you sense the ?, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0026, 0.9939, 0.0035]])
TEST DATA: @classicfm973 @bukihq @schullzz hi , would you know about the george benson show tomorrow at eko hotel ? how can one get tickets ?, GOLD 

tensor([[0.0047, 0.0047, 0.9906]])
TEST DATA: @benjbaur done and done ! i haven't seen the last few episodes . i don't have internet until monday so i can't download them yet ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[6.5067e-04, 6.5067e-04, 9.9870e-01]])
TEST DATA: @sandyahmed4 @haithamessam i was there for international women's day in march . hope to return soon ! i love it !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[4.1675e-04, 4.1675e-04, 9.9917e-01]])
TEST DATA: @scooter70 is hoping to get him the special beer 12/12 / 12 from stone brewing comp and save it for jt for his 21st birthday . :), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0292, 0.1074, 0.8634]])
TEST DATA: registration for youth soccer has been extended to july 29th . if you haven't registered and are still interested ... http://t.co/13lstehm, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0058, 0.9800, 0.0142]])
TEST DATA: @oneyoungworld kofi annan will be addressing 

tensor([[0.0129, 0.0129, 0.9741]])
TEST DATA: bowling then dinner w / the family tomorrow for maite's birthday (:, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[4.9870e-04, 4.9870e-04, 9.9900e-01]])
TEST DATA: so , @chuckragan in helsinki tonight with the #revivaltour , and he has a birthday ! sounds like a killer combination . too bad its tuesday ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0019, 0.9963, 0.0019]])
TEST DATA: the newer new ipad aka the ipad 4th generation with retina display http://t.co/vch9pxnk #apple #new, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0042, 0.0042, 0.9916]])
TEST DATA: we'll be at food day omaha this sunday , 10/21 , 9 am - 1 pm , sampling cookie-inspired smoothies with girl scouts ... http://t.co/dnprjzcr, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[5.6936e-04, 9.9886e-01, 5.6936e-04]])
TEST DATA: we're not dead yet , just busy setting up figments media . we promise to have an update sometime monday , do y

tensor([[0.0019, 0.0019, 0.9962]])
TEST DATA: got floor seats for bon jovi in april ! i can't wait ! dead or alive , livin ' on a prayer , or going out in a blaze of glory . #superstoked, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[1.2844e-04, 1.2844e-04, 9.9974e-01]])
TEST DATA: last day in scottsdale is tuesday , so happy to be going back to tempe ! :), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[1.1055e-04, 1.1055e-04, 9.9978e-01]])
TEST DATA: harrogate is a spa town and the site for the great yorkshire show in july . this cottage is a great base for visiting http://t.co/zypjzgai, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0290, 0.1021, 0.8688]])
TEST DATA: @justjimwilldo ah , in nz it's labour day ( last monday in oct ) . besides i figured it's a bit warmer in bendigo than melbourne . we shall see ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0155, 0.9081, 0.0764]])
TEST DATA: playa vista baby boom leads to a new school playa vista e

TEST DATA: eldora speedway - new weston , oh - saturday , june 30th - who is coming to get the $ 5000 ? lee cooper , max blair , ... http://t.co/7sjrwyjs, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0228, 0.8103, 0.1669]])
TEST DATA: only 3 more days until africaid's mother's day shopping night at ten thousand villages ! ! friday the 11th from 5-8 pm !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0197, 0.8745, 0.1058]])
TEST DATA: ipad hd hits stores tomorrow . will you be waiting in line for one ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[7.4445e-04, 7.4445e-04, 9.9851e-01]])
TEST DATA: @rowanruless since before pmr :d hehehe . ooh mitchie asked me to tell you you're invited to her sweet 16th ! hehehehe, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0025, 0.9946, 0.0029]])
TEST DATA: hindu no secrecy about it policy , says chandy : chief minister oommen chandy said here on thursday that there was ... http://t.co/u8kwyel3, GOLD LABEL: n

tensor([[0.0435, 0.3416, 0.6150]])
TEST DATA: derrick rose , you eat pussy and break ya neck modasucka loll " black friday " @michaelblackson http://t.co/90vpw3vw, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0180, 0.8667, 0.1153]])
TEST DATA: here's your chance to meet jim rogers and milk bellafiore this coming saturday ! i have got the platinum vvip ... http://t.co/frk6digc, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0295, 0.7977, 0.1727]])
TEST DATA: starkville saturday ! i might just wear my ole miss stuff haha #not, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0015, 0.9967, 0.0018]])
TEST DATA: forget the 10 hour bus trips ! now you can fly from subang to hat yai comfortably in just 1 hour 20 mins . the 1st ... http://t.co/ykd7iday, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0172, 0.8940, 0.0888]])
TEST DATA: apple special event live bloganother always-exciting apple event ! join us october 23 as we update live from the ... http:/

tensor([[0.0041, 0.0041, 0.9917]])
TEST DATA: @hyungjun87 hyung jun oppa i love you, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0024, 0.0024, 0.9952]])
TEST DATA: you can be a ' switch on superstar ' ! every saturday , u get chance to turn on blackpool illuminations - it could be you ! text lights to 80039 !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0070, 0.9753, 0.0177]])
TEST DATA: @mikarublackline yo ! see u in helsinki ( again :p ) december 14th yeeey ~ last time u were here with dio ^ ^ ', GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0158, 0.9319, 0.0523]])
TEST DATA: @northstandchat despite recent performances lets make sure 25k albion fans make amex a total noise cauldron on friday # nonstopsinging, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.9424e-05, 9.9996e-01, 1.9424e-05]])
TEST DATA: so i may or may not be able to afford snsd's new japanese album . > _ < not that deluxe version anyway . maybe i'll get the normal one ., GO

tensor([[0.0415, 0.3748, 0.5836]])
TEST DATA: @tjariyo haha did you hear on friday when i like shouted fock me in a liverpudlian accent xd tate was just like - _ -, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[3.3317e-05, 9.9993e-01, 3.3317e-05]])
TEST DATA: wed . am , my two part interview with blues legend edgar winter . listen to 98.1 free fm at 6:20 and 8: 10am . he's at bluesfest on sat ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[6.4303e-04, 9.9871e-01, 6.4303e-04]])
TEST DATA: did u know that the official celebration of pi day ( mar 14 or 3/14 ) starts at 1:59 to represent 3.14159 ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[7.3502e-04, 7.3502e-04, 9.9853e-01]])
TEST DATA: ive just heard the edinburgh derby has been moved to the 3rd of jan . is this true ? ? but as long as its still a night time ko im happy #pyro, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0340, 0.3207, 0.6453]])
TEST DATA: obama comes back to win 2nd debate with r

tensor([[8.4035e-05, 9.9983e-01, 8.4035e-05]])
TEST DATA: with only two weeks to go until the release of threshold's brand new studio album " march of progress " , you can ... http://t.co/ewpfawly, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.8517e-05, 1.8517e-05, 9.9996e-01]])
TEST DATA: thanks so much to all of you who came to the remembrance service on the 11th . i had a great time and i love ... http://t.co/rc9nb7z8, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0027, 0.9940, 0.0033]])
TEST DATA: @__takiyah hmm if this friday is the 28 then it's away at seaholm . next home is hc :(, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0315, 0.5452, 0.4233]])
TEST DATA: #vote4urdayumself comedy show w / @ali_speaks tomorrow @ the houston improv , 7:30 pm . free show ! get #register2vote or #pledge2vote to enter ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0068, 0.9759, 0.0173]])
TEST DATA: jim rogers is also responsible for laying off 1,900 n

tensor([[0.0030, 0.0030, 0.9940]])
TEST DATA: ahhhh the next few weekends are going to be messy ! first off - this saturday : powder room at the gladstone hotel ... http://t.co/c04kqknr, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0344, 0.7346, 0.2310]])
TEST DATA: i just bought : ' danny elfman & tim burton 25th anniversary music box ' by tim burton via @amazon http://t.co/dqqgycel, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[6.9160e-05, 6.9160e-05, 9.9986e-01]])
TEST DATA: @divine_mms hi there vinny , i heard u'l be in " wansapanataym " this coming sat . and i am sooo excited to see you on t . v . , i love you vinny <3, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0146, 0.0233, 0.9621]])
TEST DATA: have to go stand at the apple store like a right dork tomorrow to upgrade my recently purchased ipad 3 for the ipad 4 . sigh . #1stworldproblems, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0028, 0.9926, 0.0046]])
TEST DATA: nikki beach miami 

tensor([[0.0189, 0.0546, 0.9265]])
TEST DATA: pop in to the gladstone hotel with mommy and strollers for free coffee and socializing mon-fri 10:00 a . m . to 4:00 ... http://t.co/irai7c77, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0082, 0.9695, 0.0223]])
TEST DATA: @site_v why would i steal mejibray and kiryu stuff ? i don't listen to them ~ but i may mess with the shipping so it will arrive late hahaha, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0013, 0.9975, 0.0013]])
TEST DATA: just got a craving for candy cane hot chocolate . is it december yet ?, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0321, 0.6081, 0.3599]])
TEST DATA: #ngsgigpick just had a special moment , a duet between @hugoracemusic & @leekofficial on the 1st night of mr hugo race's australian tour ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[1.6517e-04, 1.6517e-04, 9.9967e-01]])
TEST DATA: first song i luvd by the boys : moments , 2nd : up all night , uan album comes

tensor([[0.0060, 0.9833, 0.0107]])
TEST DATA: @maddow ole miss band is fired up for rousing verion of dixie next tuesday night-wanna sing it rachel ?, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[5.6340e-04, 5.6340e-04, 9.9887e-01]])
TEST DATA: @smashleychavez 9k day ! they just honored matt cain . gave him the key the city and made every june 13th from here forward matt cain day !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0098, 0.9446, 0.0456]])
TEST DATA: tomorrow is the last day to register for youth soccer , youth volleyball and tiny tot soccer ! - http://t.co/xmqloj8j, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0378, 0.3807, 0.5814]])
TEST DATA: so ... i may go play some me3 now ... mainly just trying to level up since i promoted all classes and the only ones above 15 are adept ..., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0044, 0.9872, 0.0084]])
TEST DATA: excuse the connectivity of this live stream , from baba amr , so many 

TEST DATA: " cao cao may have his zhang liao , but i can match him with my friend gan ning . " - sun quan, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0386, 0.1984, 0.7630]])
TEST DATA: is it sad that if i didn't have pom on thursday i would go and see catelynn and tyler from teen mom speak ?, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0071, 0.0071, 0.9859]])
TEST DATA: judas kiss on friday , horse riding in hype park and shopping yesterday , bbc tour and westfields and dinner with friends today . good weekend ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0014, 0.0014, 0.9971]])
TEST DATA: don't miss the tron reunion with cindy morgan , @cindymorganinfo and bruce boxleitner , @boxleitnerbruce at phoenix comicon in may ! #phxcc ~ sm, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0343, 0.3342, 0.6314]])
TEST DATA: free pick friday was strong this weekend with ohio state #steelers , and #falcons getting the job done . enjoy #mnf ! http:/

tensor([[2.0486e-04, 9.9959e-01, 2.0486e-04]])
TEST DATA: i was dreaming when i was reminded that i have to take the act tomorrow, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0037, 0.0037, 0.9927]])
TEST DATA: i want a 16th birthday like my super psycho sweet 16 with extra pyscho ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0213, 0.0306, 0.9481]])
TEST DATA: the graduate @_mslee_ and janee no wait renee or danee or was it shanee no it may be lanee * shrugs * http://t.co/qjcqqhdt, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0222, 0.0483, 0.9294]])
TEST DATA: @cw_network bummed we don't get to see arrow until saturday because of the chicago bulls game ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0040, 0.0040, 0.9921]])
TEST DATA: baby colton is a saint bernard ! ! ! i may have the cutest godson in ze world ! ! ! @fricknatalie http://t.co/1thnrn0r, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0149, 0.0208, 0.9644]])
TEST DAT

tensor([[0.0028, 0.9944, 0.0028]])
TEST DATA: barcelona's carles puyol out 8 weeks with dislocated elbow suffered in champions league win tuesday, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0042, 0.9863, 0.0095]])
TEST DATA: check out derby on the big screen at tomorrow night's screening of @derbybabyfilm at creative alliance ! http://t.co/c7499uax, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0174, 0.0209, 0.9617]])
TEST DATA: the boys started rehearsing ? reminds me of alive ina 2nd day's fantastic baby rehearsal :( vips went crazy outside , sang along together, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[4.3221e-04, 4.3221e-04, 9.9914e-01]])
TEST DATA: my birthday is an hour away & i'm crying . lol great . tomorrow should be great ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[9.7790e-04, 9.9804e-01, 9.7790e-04]])
TEST DATA: miley cyrus with employee of hollywood tans ( 11th & walnut ) after tanning there wednesday night . http://t.co/

TEST DATA: @actorbrianwhite plays lt . joe bishop on the hit new series #beautyandthebeast ! ! check it out every thur . 9/8 c on cw network ! !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0176, 0.0242, 0.9582]])
TEST DATA: @bullbeggar jan , i just spoke to joe zellner & smb team , they are fine . we even had two couples who went ahead with their weddings today :) ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0012, 0.9975, 0.0012]])
TEST DATA: " @bbcburnsy : loads from sb ; talks with chester continue ; no deals 4 out of contract players ' til jan ; dev t roth , coops to chest'ld #hcafc ", GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0311, 0.2175, 0.7514]])
TEST DATA: i'm taking the cahsee ( i've never taken it bitches so stfu ) csu & uc applications are in progress , and i'm taking the sat saturday . fuck - . -, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0049, 0.9864, 0.0087]])
TEST DATA: eagles of death metal definitely get you goin

tensor([[0.0029, 0.9937, 0.0034]])
TEST DATA: november days of gratitude day 25 - thanksgiving leftovers - i've eaten them every day since thanksgiving and i'm ... http://t.co/c64c0glr, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0295, 0.7040, 0.2665]])
TEST DATA: http://t.co/jjvdi4lw wednesday's featured property of the day is knollwood place apartments , in ... http://t.co/wnc7tp7b, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0262, 0.6614, 0.3124]])
TEST DATA: http://t.co/zp19hxd7 - have you heard of the " 39 steps " ? a sneak peak of the national award winning play . this saturday at music academy !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0129, 0.0183, 0.9689]])
TEST DATA: ask me about the food expo - abj food festival at the eagle square abuja 7th - 9th dec ' 12 . rock bottom prices on food for the festive season !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[2.6121e-04, 2.6121e-04, 9.9948e-01]])
TEST DATA: @emilybeasley5 emilyyyy

TEST DATA: holi ... cuantas on ? para volvernos crazy , crazy , crazy till we see the sun xx, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0100, 0.9590, 0.0310]])
TEST DATA: this week's #tweetpic66 contest is tweeting a picture with a mario lemieux signed item ! winner chosen randomly friday at 2pm !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0013, 0.0013, 0.9973]])
TEST DATA: we " get together ... so we can " get it together ! " join us for a women's day celebration on dec . 1st ! ! http://t.co/7mtxb4wt, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0197, 0.8980, 0.0822]])
TEST DATA: there's going to be a baby boom about 9 months after december 21, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0013, 0.9973, 0.0013]])
TEST DATA: i'm going to threshold at celebr 8.2 festival in kingston upon thames , united kingdom - may 11 http://t.co/mcuown5c, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0037, 0.9865, 0.0098]])
TEST DATA: maske

tensor([[0.0027, 0.0027, 0.9946]])
TEST DATA: @smithwhitney i think a trip to the good old orono on the 17th or 18th would be a fab idea :), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0325, 0.4002, 0.5673]])
TEST DATA: we just received more tickets for blue rodeo at the kee to bala saturday may 19th and sunday may 20th . tickets ... http://t.co/vbpol3zv, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[3.5714e-04, 3.5714e-04, 9.9929e-01]])
TEST DATA: @raffthenurse @carolinekin - the sun is shinning so happy nurses day !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0011, 0.0011, 0.9979]])
TEST DATA: i'm performing at this benefit with @wyattish tonight mike d is djing as well gonna be fun ! http://t.co/8fsxaj0z #lefooding #benefit, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0038, 0.9907, 0.0055]])
TEST DATA: rndm has a beef with canada . tonight in montreal @theatrecorona . tomorrow night ottawa @algonquincolleg commons theatre http://t.co/di

tensor([[0.0242, 0.0715, 0.9043]])
TEST DATA: we're counting down the days ! ... the #orlando home and garden show and boat show begins this friday ! http://t.co/mw6ejbp7, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0035, 0.0035, 0.9931]])
TEST DATA: hot springs to mt . nebo last sunday with wife driving a ferrari ? not , my wifes hyundai veloster cool po folks ... http://t.co/dk8ehsee, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0023, 0.9953, 0.0023]])
TEST DATA: " .. omar shaban says the gaza strip may be poor but the west bank's aid-in ... " hamas brinkmanship masks quiet confidence http://t.co/rvdzukpw, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0024, 0.0024, 0.9953]])
TEST DATA: @lancemcalister excitement for the bearcats tomorrow night obviously . :), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0168, 0.0288, 0.9545]])
TEST DATA: @j9neverlose traveling the whole circuit ? cleveland can be pretty dismal in march ... unless you're d

TEST DATA: whoo ! clippers won the season opener ! the lakers are now 0-2 . the battle of l . a . starts friday . let's go ! :) #clippernation, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0012, 0.0012, 0.9975]])
TEST DATA: @gary_grant1991 yeah honestly , going up to see my gran plus my cousin got tickets for the edinburgh derby on sunday . yeah course you can, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0115, 0.9486, 0.0399]])
TEST DATA: 1st points to sunnybank in premier rugby grand final , with a penalty kick to dion taumata #3rdtier, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[8.1378e-04, 9.9837e-01, 8.1378e-04]])
TEST DATA: a cape town woman died on the eve of her 21st birthday when she was knocked down on the n2 highway , the cape argus reports today ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0045, 0.0045, 0.9909]])
TEST DATA: filming starts on wednesday ! and the second project is already in the works ( hopefully ) . exciting t

tensor([[0.0030, 0.9924, 0.0046]])
TEST DATA: the gazette reported on problem of cyclists flouting the law at the top of the town . now the police are cracking down . see thurs gazette ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[4.2540e-04, 4.2540e-04, 9.9915e-01]])
TEST DATA: just seen @jonasbrothers at radio city and now get to see then again on the 28th ! ! so excited ! ! !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0044, 0.9871, 0.0085]])
TEST DATA: @chloephillipa gazza , ramirez , cork back and we'll do well . then add some defenders in january and we'll climb up the league ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0015, 0.0015, 0.9970]])
TEST DATA: congratulations to jessica lee morgan , who placed 3rd runner up tonight at miss teen usa . jessica also won miss ... http://t.co/gjwniwuw, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0263, 0.7772, 0.1965]])
TEST DATA: sir , there are enemies in the white house.something needs

tensor([[3.9488e-04, 9.9921e-01, 3.9488e-04]])
TEST DATA: @carlastrauss i'm from halifax , nova scotia . not sure if we will go on march break , i'll have to see as it gets closer . why ?, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0147, 0.9150, 0.0703]])
TEST DATA: bolton wanderers have sacked manager owen coyle following a poor start to the season . the club currently sit in 18th in the championship ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[2.5245e-04, 9.9950e-01, 2.5245e-04]])
TEST DATA: busy week 4 us : @12thplanet at @vertigoclubkl on the 12th , @mysteryjets at @stageclubkl on the 15th n noah at kl live on the 16th , u comin ?, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.9492e-05, 9.9996e-01, 1.9492e-05]])
TEST DATA: via @nbcdfwweather : latest computer information supports rainfall of 1-2 " in the metroplex thru tomorrow . higher amounts likely south of i - 2, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.5042e-04, 9.9970e-01, 1

TEST DATA: @blackhawksbabyx look for a live version of " just older " , it's one of my favorites . and if they play " blaze of glory " in july , i'll die . <3, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0153, 0.9244, 0.0603]])
TEST DATA: postseason prep is underway . big east quarterfinal vs . either uc or marquette is saturday at card park . are you ready ? http://t.co/etfklroz, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.2279e-04, 9.9975e-01, 1.2279e-04]])
TEST DATA: does anyone have photos from the @drake show this past saturday at the kee ? one of our own , @kendallhm was on stage ! @muskokabala, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[2.7288e-05, 9.9995e-01, 2.7288e-05]])
TEST DATA: bnp opposes companies act change : the bnp on tuesday asked the government to drop the move to change companies a ... http://t.co/avrh5j4g, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[5.0847e-06, 9.9999e-01, 5.0847e-06]])
TEST DATA: idk if i should see

tensor([[9.1480e-04, 9.9817e-01, 9.1480e-04]])
TEST DATA: watching pll halloween event for the 4th time and im still shaking lol, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0356, 0.5275, 0.4369]])
TEST DATA: omg ! ! ! just saw on e news that harry kissed niall at the texas concert on sunday ! ! fangirling ! ! !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0040, 0.0040, 0.9921]])
TEST DATA: cause it's friday 13th , i'm watching my super psycho sweet 16 part 1 & 2 #youknowyolo, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0201, 0.0667, 0.9132]])
TEST DATA: so i'm listening to this beatles ' playlist to study for my beatles midterm on friday , and fucking snsd is one of the related videos . #wtf, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0283, 0.7874, 0.1843]])
TEST DATA: @evanmatheney you may like this . dude from dashboard confessional , playing with a band that he started awhile back . https://t.co/c49uoncc, GOLD LABEL: positive, GOLD 

tensor([[0.0291, 0.5869, 0.3840]])
TEST DATA: #teamfollowback la liga : barca and betis march on , malaga held : real betis moved up to fourth in the table after ... http://t.co/ps13rwfa, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0015, 0.0015, 0.9970]])
TEST DATA: the pacers are counting on paul george to step up , gerald green and dj augustin are your adds ... nat 2nd in the east , son ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[3.3129e-04, 3.3129e-04, 9.9934e-01]])
TEST DATA: de la soul is going to be at the cabooze on 4/27 ... that is going to be a great show ..., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0239, 0.0782, 0.8979]])
TEST DATA: did you see girl scouts on the @kare11 morning show for #cdos on saturday ? here's the video : http://t.co/vyeottk8, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[2.3173e-05, 9.9995e-01, 2.3173e-05]])
TEST DATA: star wars weekends wraps up tomorrow . here's the weekend's event guide . anyone going 

tensor([[0.0191, 0.0446, 0.9363]])
TEST DATA: carles puyol could be out for up to 6 weeks after straining knee ligaments . further tests on the barca man tomorrow - http://t.co/rfnj8osa, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0099, 0.0099, 0.9803]])
TEST DATA: mix six pack from warners at the bay tonight . bitter & twisted beer festival tomorrow . i love my #craftbeer, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0037, 0.9888, 0.0075]])
TEST DATA: register today to attend a free ! super saturday , october 27 in syracuse , new york with president , nigel branson ! - http://t.co/iz0d3sok, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[1.1673e-04, 9.9977e-01, 1.1673e-04]])
TEST DATA: @johnmuttimer retweet pls : west-end star michael ball with cork youth orchestra , dec 8th & 9th , city hall . tickets from ticketmaster.ie, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0281, 0.1444, 0.8275]])
TEST DATA: we can take the big bucket to the millio

tensor([[2.9877e-05, 9.9994e-01, 2.9877e-05]])
TEST DATA: heads up : galaxy s ii can be wiped by just clicking a link , other touchwiz devices may also be vulnerable - http://t.co/1qomut8a / r, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[4.0341e-05, 9.9992e-01, 4.0341e-05]])
TEST DATA: the vintage club at indian wells . ranked 21st in the state by golf digest , this place was so exclusive when it ... http://t.co/0kbsh9ni, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[5.1359e-04, 9.9897e-01, 5.1359e-04]])
TEST DATA: dj mix n match spinning live to air with z103 . 5 this wednesday october 31st at city nightclub ! http://t.co/4d3qxmid, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0146, 0.0247, 0.9607]])
TEST DATA: @ericggooden met you at the w , espy awards . look forward to seeing you sat , on the red carpet - bobby kimball , eddie mon http://t.co/3qgd9fvo, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0295, 0.6671, 0.3034]])
TEST DATA: oy . don'

tensor([[0.0196, 0.8298, 0.1506]])
TEST DATA: although the rain is falling , the sun is always shining at cheddar , almondsbury and lechlade ! what is everyone up to today ?, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0061, 0.9797, 0.0142]])
TEST DATA: mehdi hasan enraging twitter on a sunday ? c'mon , at least give us a day off ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[5.0442e-04, 9.9899e-01, 5.0442e-04]])
TEST DATA: the celtics celebrated their new year on nov 1 . it marked the end of summer , darker half of the year , beginning of cold winter #hybridfacts, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0451, 0.4096, 0.5453]])
TEST DATA: dad just said if obama wins on tuesday he is moving to cuba #dontknowwhatyourtalkingbout #butok, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[6.0525e-04, 9.9879e-01, 6.0525e-04]])
TEST DATA: august 4th 2012 catch me live at pomona fairplex for @rnblivepomona with @case_music , @joethomas563 , @donellj

tensor([[0.0237, 0.0509, 0.9254]])
TEST DATA: 25 - year-old dallas seavey wins iditarod - dallas seavey won the iditarod trail sled dog race tuesday , becoming the y ... http://t.co/xf2rv257, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0346, 0.5923, 0.3731]])
TEST DATA: @annavonwinter im sad i never saw you at phoenix comicon but i didnt spend much time in the exhibition hall after friday ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[4.9467e-04, 9.9901e-01, 4.9467e-04]])
TEST DATA: . @cherylcole ' s on mtv hits in 30 minutes taking us behind the scenes of her " under the sun " video, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0034, 0.9911, 0.0055]])
TEST DATA: #news pepe reina believes the stylish manner of liverpool's 3-0 victory over fc gomel on thursday ... http://t.co/dw3dea5k ( lfc website ), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[1.7659e-04, 1.7659e-04, 9.9965e-01]])
TEST DATA: @iloveerika_x3 <3 ... but you really shiuld go to

tensor([[0.0304, 0.0981, 0.8716]])
TEST DATA: child support division of hosts employers symposium " bridging the gap " this friday #guam . http://t.co/elethjsl, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[8.5257e-04, 8.5257e-04, 9.9829e-01]])
TEST DATA: mark cuban : apple tv is a pipe dream and why the hdnet founder thinks that may be a good thing ( mike shields / adw ... http://t.co/l0ebf8hc, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0277, 0.7099, 0.2624]])
TEST DATA: day 4 of hat yai ! saturday - sunday going to songkla , then to phuket . yey ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0037, 0.9912, 0.0051]])
TEST DATA: danny elfman's score for " the silver linings playbook " just may be the oddest but most intriguing score he's composed since " sleepy hollow " ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0312, 0.7379, 0.2309]])
TEST DATA: and whilst listening to dashboard with a hangover , i may as well slit my wrists, GOLD LABE

tensor([[0.0021, 0.9950, 0.0029]])
TEST DATA: 2012 espy awards : wednesday night ( july 11 ) was dedicated to the athletes . the television channel espn hold the ... http://t.co/sj0wblkz, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[6.2878e-05, 9.9987e-01, 6.2878e-05]])
TEST DATA: " @rafaelnadalfc : rafa will play his third round match at the bnp paribas open at indian wells on tuesday against marcel granollers . ", GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[3.6820e-05, 9.9993e-01, 3.6820e-05]])
TEST DATA: in tomorrow's debate , if romney is half as sharp as he was in this earlier exchange with gingrich ... obama is toast : http://t.co/bi5pnvmr, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[8.9297e-05, 8.9297e-05, 9.9982e-01]])
TEST DATA: @missbriteside go you , well done ! glad ur legs stayed loyal lol . i'm back tomorrow too . jiujitsu went well thanks #funkyjiujitsu love it . x, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[2.1227e-04, 9.9958e-

tensor([[5.2443e-04, 5.2443e-04, 9.9895e-01]])
TEST DATA: @hugofeijo that pic is 9th and superior , ; looking eastward down superior ave . its the corner my mom always stands for st patricks day parade, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0118, 0.9485, 0.0397]])
TEST DATA: tonight at midnight ends sober october - and it's halloween ! look out myrtle beach ! ;), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0033, 0.9915, 0.0052]])
TEST DATA: when nba trades become official july 11th - i hear atl buys out the contract of jordan farmar . he will sign with a turkish team ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0342, 0.2369, 0.7288]])
TEST DATA: york football staff member has leaked that york's goal is to score 100 points against us and leave in 1st string for the whole game #true, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0318, 0.2463, 0.7218]])
TEST DATA: watch @trackjenny reflect on her 2nd place finish at the london grand

tensor([[0.0383, 0.2317, 0.7300]])
TEST DATA: watching les mis 25th anniversary concert . how long before the boy jonas gives me rage , knowing michael ball was backstage ?, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0386, 0.4870, 0.4744]])
TEST DATA: @jacksierra1 say hello tomorrow from your high status line up and i shall hail to the vips, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0013, 0.0013, 0.9975]])
TEST DATA: i don't like testing i'm glad i don't have to worry about the cashee anymore on may . 8th (: passed that shxt !, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 2
tensor([[0.0185, 0.8935, 0.0880]])
TEST DATA: richard bland is going to be my plan b , i need to talk to my guidance counselor tomorrow ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.9884e-04, 9.9960e-01, 1.9884e-04]])
TEST DATA: anybody want to play some football tomorrow in doral around 530 ? hit me up, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[6.0966e-05, 6.0966

tensor([[0.0116, 0.9415, 0.0469]])
TEST DATA: burgundy wave : los angeles galaxy vs colorado rapids - game preview : on friday september 14th the colorado rapid ... http://t.co/f2rzkl1b, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[3.0037e-06, 9.9999e-01, 3.0037e-06]])
TEST DATA: this weekend daylight saving time ends . be sure to set your clocks back one hour before going to bed on saturday night ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0241, 0.0748, 0.9011]])
TEST DATA: @msynergy i totally just squealed seeing the abc sunday promo on tv . the charmings ! all the feels , i have them !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0089, 0.0089, 0.9821]])
TEST DATA: ahh , the polish festival is today and tomorrow ! shoooooooooot . i hope i can make it tomorrow : s, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0342, 0.4207, 0.5451]])
TEST DATA: dtn cricket : pattinson may be saved for a tour ahead of ashes : james pattinson may not make

tensor([[0.0121, 0.0121, 0.9759]])
TEST DATA: tia sharp's funeral today , may she rest in perfect peace ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0178, 0.0423, 0.9400]])
TEST DATA: why sustainability is very important for the cotton industry : interlaken , 9 october 2012 . in this vide ... http://t.co/2obcfvjt #wcoc09, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[9.8119e-04, 9.8119e-04, 9.9804e-01]])
TEST DATA: i can't wait to see all the riot fights in miami on worldstarhiphop tomorrow, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0413, 0.4963, 0.4624]])
TEST DATA: because you know that no matter how shitty you feel on a tuesday morning , maite feels shittier ., GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0046, 0.0046, 0.9909]])
TEST DATA: holy shit the guy who made kony 2012 is gonna be on the today show tomorrow . guys hes still alive #kony2012 #kony2012, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0053, 0.0053, 0.9894

tensor([[0.0423, 0.2946, 0.6630]])
TEST DATA: ok unless i hear some outrageous rumor ... im cop heemfording the ipad hd by friday, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0076, 0.0076, 0.9848]])
TEST DATA: @xcdrichard @philtonks2 are the big hst sets innocent , going to be on an xc one saturday, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0016, 0.0016, 0.9969]])
TEST DATA: i went to the polish festival on roncesvalles on saturday awesome time ! http://t.co/juexx8gb, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[1.1169e-05, 9.9998e-01, 1.1169e-05]])
TEST DATA: i posted 10 photos on facebook in the album " super saturday at adam rogers park " http://t.co/nqjpjsvl, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0049, 0.0049, 0.9902]])
TEST DATA: @priceyledge alright pricey ! how you doing , got a round in lough erne next friday ! #needmoreballs, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0024, 0.0024, 0.9952]])
TEST DATA: excited 

TEST DATA: @mrnickclark it's a formal disqualification as the match v ivory coast was abandoned . they may also face a ban from 2015 tournament ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0023, 0.0023, 0.9954]])
TEST DATA: @scottburkholder lovely event thursday at the creative alliance - - congrats !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0276, 0.1250, 0.8474]])
TEST DATA: 2012 espy awards best dressed : the 20th annual 2012 espy awards were last night , and with lebron james winning ... http://t.co/7suzkkgd, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[4.3699e-04, 9.9913e-01, 4.3699e-04]])
TEST DATA: i have a spare ticket for the warners at the bay beer festival on sunday , anyone want it ?, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0122, 0.0122, 0.9755]])
TEST DATA: mad tired , gotta get up early to work out , and i have work like all day tomorrow but yet i'm still up wait for @elsarcasmmm lol smh # <3, GOLD LABEL: negative, 

tensor([[0.0145, 0.0145, 0.9710]])
TEST DATA: miss teen usa on the next one .. saturday wahhh ? (:, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0292, 0.0935, 0.8773]])
TEST DATA: i really want for there to be bball on sunday . and not just mysa, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[4.5776e-05, 9.9991e-01, 4.5776e-05]])
TEST DATA: @ajaydevgn himmatwala set for holi release 29 march 2013 .. sure shot another blockbuster 4 ajay.it will going 2 3rd in row .. bb , sos , himmatwala, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[2.3738e-04, 2.3738e-04, 9.9953e-01]])
TEST DATA: cold front in the metroplex ! happy friday ! :) http://t.co/tuvyo9kq, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0044, 0.9895, 0.0061]])
TEST DATA: @monzzz330 were fucking going to taco bell tomorrow, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[9.9382e-06, 9.9998e-01, 9.9382e-06]])
TEST DATA: i posted 23 photos on facebook in the album " abbey dawn at new y

tensor([[0.0022, 0.0022, 0.9957]])
TEST DATA: vanilla fudge , friday nite . tanner park copiague ny . free concert on the water . no mark stein . what an amazing ... http://t.co/ppsgr4cz, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0029, 0.0029, 0.9943]])
TEST DATA: last day of pssas tomorrow :) #yes #yeahbuddy ! ! !, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0016, 0.0016, 0.9969]])
TEST DATA: matta doesn't know how to view being ranked 4th in the country and 3rd in the big ten , except the conference must be really good ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0015, 0.0015, 0.9970]])
TEST DATA: @katvontease420 hmm i usually don't watch b / g shows but i may have to make an exception for something like that ;), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0289, 0.7884, 0.1827]])
TEST DATA: new song by 50 cent performing " riot " remix with 2 chainz 2nd song off of 50 cent's upcoming gangsta grillz ... http://t.co/akbiphzj, GOLD

tensor([[6.9725e-04, 9.9861e-01, 6.9725e-04]])
TEST DATA: if we could just send taks scores instead of sat / act my life would be a billion-trillion times easier ., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0384, 0.6286, 0.3330]])
TEST DATA: @babybaileybear [ he smiled ] it depends what type of books you like to read . i like james pattinson . they may not have those here .., GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[4.0254e-06, 9.9999e-01, 4.0254e-06]])
TEST DATA: the band has just been announced as part of the line up for the rock am ring ( june 7th ) and rock im park ( june 8th ) festivals !, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[2.8957e-04, 9.9942e-01, 2.8957e-04]])
TEST DATA: from the soundboard will feature #georgecarlin and #paulmooney wed jul 11 3 to 5am summer fund drive . #donate #money @deepdancenyc, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[1.1480e-06, 1.0000e+00, 1.1480e-06]])
TEST DATA: " @kaiology : have u gotten ur

TEST DATA: remus lupin sat in the kitchen of 12 grimmauld place , eating a piece of pie molly had given him ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0334, 0.5233, 0.4433]])
TEST DATA: juniors playing powderpuff , if you aren't at practice tomorrow you will not play , it starts at 5:30 pm , hope to see you there !, GOLD LABEL: negative, GOLD CLASS 0, OUTPUT: 1
tensor([[0.0015, 0.9970, 0.0015]])
TEST DATA: i may have caught a ufo engaging warp drive in the background of this photo . http://t.co/asy4doye, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0145, 0.9253, 0.0602]])
TEST DATA: @charlieismemate sweden eh ? how'd that come about ? not yet , sxsw will b n march . when is ur behind coming 2 the u . s . ? ;) how's the little 1 ?, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[0.0013, 0.0013, 0.9974]])
TEST DATA: buongiorno a tutti ! sun is shining another beautiful day in vanuatu : ), GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[8.4038e-04,

tensor([[0.0334, 0.3034, 0.6632]])
TEST DATA: news > flava - flava will be taking over floor 5 tomorrow night , with some of the best hip hop , afrobeats and rnb t http://t.co/pgquhnuy, GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 2
tensor([[0.0211, 0.0351, 0.9438]])
TEST DATA: night college course sorted , just have to enrole tomorrow now .. finally starting to figure out what i wanna do :-) #busyday, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 2
tensor([[0.0137, 0.9245, 0.0618]])
TEST DATA: for the 1st time in 30 years . for your splendiferous entertainment . arts in lechlade proudly presents an old ... http://t.co/qg0xaxtv, GOLD LABEL: positive, GOLD CLASS 2, OUTPUT: 1
tensor([[1.6843e-04, 9.9966e-01, 1.6843e-04]])
TEST DATA: @im_tgun @frayfenner @nvdox anyone else noticed the uncanny resemblance between tgun and petraeus ? tgun's dad may have a confession to make ., GOLD LABEL: neutral, GOLD CLASS 1, OUTPUT: 1
tensor([[0.0016, 0.0016, 0.9967]])
TEST DATA: nurses day - 12 may 2012 . n